# cmake
# 构建一个 CPack 安装包(cmake install的内容打成安装包,release版本),切换到out目录，命令行：cpack
if(CMAKE_BUILD_TYPE STREQUAL "Release")
  set(CPACK_GENERATOR NSIS)
  set(CPACK_OUTPUT_FILE_PREFIX ${PROJECT_BINARY_DIR}/installer/)
  set(CPACK_PACKAGE_NAME "${PROJECT_NAME}-installer")
  set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
  set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
  set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})
  set(CPACK_PACKAGE_VENDOR "My company")

  # set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/INSTALL.md")
  # set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
  # set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "message: a small messaging library")

  # set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
  set(CPACK_PACKAGE_INSTALL_DIRECTORY ${PROJECT_NAME})
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  message(STATUS "CPack generators: ${CPACK_GENERATOR}")
  INCLUDE(CPack)
endif()